# Generated by Django 3.2.5 on 2021-08-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakshmi_travels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcars',
            name='km_per_day',
        ),
        migrations.AddField(
            model_name='rentalcars',
            name='km_allowed_per_day',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalcars',
            name='car_id',
            field=models.IntegerField(default='0', unique=True),
        ),
        migrations.AlterField(
            model_name='rentalcars',
            name='extra_km_per_day',
            field=models.CharField(default='15', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalcars',
            name='rate_per_day',
            field=models.CharField(default='2000', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalcars',
            name='seating_capacity',
            field=models.CharField(default='4', max_length=10),
        ),
    ]
