# Generated by Django 3.2.5 on 2021-08-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakshmi_travels', '0002_auto_20210815_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcars',
            name='car_image',
            field=models.ImageField(default='default_car.jpg', upload_to='rental_car_images'),
        ),
    ]
