# Generated by Django 3.2.5 on 2021-08-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakshmi_travels', '0005_alter_customers_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(default='no_id', max_length=20),
        ),
    ]
