# Generated by Django 3.2.5 on 2021-08-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakshmi_travels', '0006_alter_customers_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='trip_price',
            field=models.CharField(default='1000', max_length=20),
        ),
    ]
