# Generated by Django 3.2.5 on 2021-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakshmi_travels', '0007_tripdetails_trip_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.IntegerField(default='0')),
                ('package_name', models.CharField(default='Tourist Destination', max_length=100)),
                ('summary', models.CharField(default='summary', max_length=400)),
                ('duration', models.CharField(default='route1', max_length=100)),
                ('details', models.CharField(default='details', max_length=1000)),
                ('availability_status', models.BooleanField(default=True)),
            ],
        ),
    ]
