# Generated by Django 3.2.5 on 2021-08-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakshmi_travels', '0009_auto_20210818_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackagedetails',
            old_name='tour_package',
            new_name='tour_package_image',
        ),
    ]
